apiVersion: gateway.solo.io/v1
kind: VirtualService
metadata:
  name: transforms-html
  namespace: transforms-demo
spec:
  # ssl_config:
  #   secret_ref:
  #     name: wildcard
  #     namespace: default
  virtualHost:
    domains:
      - "*"
    corsPolicy:
      allowCredentials: true
      allowHeaders:
        - origin
      allowMethods:
        - "*"
      allowOrigin:
        - "*"
      exposeHeaders:
        - origin
    routes:
      - matcher:
          methods:
            - GET
          prefix: /grpc-demo/
        routeAction:
          single:
            destinationSpec:
              grpc:
                function: Render
                parameters:
                  path: /grpc-demo/{documentId}
                package: api
                service: HtmlService
            upstream:
              name: CHANGE_ME
              namespace: gloo-system
        routePlugins:
          # headerManipulation:
          #   # add headers to all responses
          #   # returned by this route
          #   responseHeadersToAdd:
          #     - header:
          #         key: Content-Type
          #         value: text/html
          #     - header:
          #         key: Location
          #         value: 'https://www.google.com/'
          #     - header:
          #         key: status
          #         value: '201'
          transformations:
            responseTransformation:
              transformationTemplate:
                headers:
                  ":status":
                    text: "301"
                  location:
                    text: "https://www.google.com/"
                # body:
                #   text: "{{ document }}"
                # text: "<head><title>Test</title></head><body><div><p>Hello {{ document }}</p> </div> </body>"
      - matcher:
          methods:
            - GET
          prefix: /http-demo/
        routeAction:
          single:
            upstream:
              name: CHANGE_ME
              namespace: gloo-system
        routePlugins:
          transformations:
            responseTransformation:
              transformationTemplate:
                headers:
                  ":status":
                    text: "301"
                  location:
                    text: "https://www.google.com/"
